spring:
  application:
    name: tracing-sampleebflux
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"    
  level:
     '[reactor.netty.http]': debug    
management:
  tracing:
    propagation:
      type: b3  